trigger: 'none' # will disable CI builds entirely
# - master
pr: none
# - master
# - releases/*

jobs:
- job: WebApp
  displayName: 'Build Web App'
  pool:
    vmImage: 'windows-2019'
  variables:
    BuildConfiguration: release
  
  steps:
  
  - task: UseDotNet@2
    displayName: Install .NET 6 sdk
    inputs:
      packageType: sdk
      version: 6.0.x
      installationPath: $(Agent.ToolsDirectory)/dotnet


